FROM python:3.10-slim

RUN apt-get update && apt-get install -y ffmpeg libsndfile1
RUN pip install numpy==1.23.5 basic-pitch==0.4.0 tensorflow==2.12.0
RUN pip install "basic-pitch[tf]"

CMD ["python", "-c", "import basic_pitch; from basic_pitch.midi import write_midi; print('Success! All modules imported.')"] 