services:
  - type: web
    name: audio-to-midi-api
    env: python
    plan: standard
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: ALLOW_ANONYMOUS_ACCESS
        value: "true"
      - key: MALLOC_ARENA_MAX
        value: "2"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: "true"
    healthCheckPath: /health
    autoDeploy: false
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 90 