services:
  - type: web
    name: audio-to-midi-api
    env: docker
    plan: standard
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        value: https://gshaarazegavljkgqgec.supabase.co
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: ALLOW_ANONYMOUS_ACCESS
        value: "false"
      - key: ALLOW_INTERNAL_NETWORK
        value: "false"
    healthCheckPath: /health
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 90 