services:
  - type: web
    name: audio-to-midi-api
    env: python
    plan: standard
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 1 --threads 2 main:app --bind 0.0.0.0:$PORT --timeout 300 --graceful-timeout 300 --keep-alive 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: ALLOW_ANONYMOUS_ACCESS
        value: "true"
      - key: MALLOC_ARENA_MAX
        value: "2"
      - key: PYTHONUNBUFFERED
        value: "true"
    healthCheckPath: /health
    autoDeploy: false
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 90 