name: Push to Replicate

on:
  push:
    branches: [main]  # Run on any push to main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  push-to-replicate:
    runs-on: ubuntu-latest
    environment: replicate  # Specify the environment where the secret is stored
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Install cog
        run: |
          sudo curl -o /usr/local/bin/cog -L "https://github.com/replicate/cog/releases/latest/download/cog_$(uname -s)_$(uname -m)"
          sudo chmod +x /usr/local/bin/cog

      - name: Use Replicate token to log in
        run: |
          echo "${{ secrets.REPLICATE_API_TOKEN }}" | cog login --token-stdin
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Push to Replicate
        run: |
          cd replicate-basic-pitch
          cog push r8.im/jgoldsmith27/basic-pitch
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }} 